### PR TITLE
update to README.md for Fedora 31

### PR DESCRIPTION
**Pull request by JA52A2A**
Change instructions for meson and ninja. Added other dependencies for building and new instructions. Instructions taken from here:
https://www.reddit.com/r/thinkpad/comments/8kh2hh/fedora_28_t460p_and_other_138a0090_fingerprint/

### CODE REVIEW

**Comment by JA52A2A** [comment]
Not sure this will be needed with the changes to Fedora 32 and Ubuntu 20.04 but it's there if need be.

**Comment by spxak1** [comment]
Hi, original poster of that linked reddit post here. 
What is happening with Ubuntu 20.04? libfprint-2 is now a thing, nothing works.

Thanks.

**Comment by JA52A2A** [comment]
Looks like ubuntu was working on adding a shim layer to get more fingerprint readers working. Not sure it will work for this specific model fingerprint reader. That's why I went ahead and the pull request.
https://github.com/freedesktop/libfprint/commits?author=3v1n0
You can see a lot of commits to libfprint from the author of this repo.

**Comment by 3v1n0** [comment]
I've some code ported already, but I had no time to finish it yet.

I hope will be able soon.

**Comment by JA52A2A** [comment]
If you get time to finish it, I'd be glad to test on Fedora 32 and update the README.md if need be.

**Pull request closed without merging**
